// Generated by LiveScript 1.3.1
viewParameters.needviews = function(){
  return {
    options: {
      find: {
        url: {
          $exists: true
        }
      },
      sort: {
        viewCount: 1,
        clickCount: 1,
        postedAt: -1
      }
    }
  };
};