// Generated by LiveScript 1.3.1
(function(){
  Meteor.startup(function(){
    var PostsNeedCommentsController;
    PostsNeedCommentsController = PostsListController.extend({
      view: 'needcomments'
    });
    return Router.route('/needcomments/:limit?', {
      name: 'posts_needcomments',
      controller: PostsNeedCommentsController
    });
  });
  viewsMenu.push({
    route: 'posts_needcomments',
    label: 'Need Comments'
  });
}).call(this);
