// Generated by LiveScript 1.3.1
var out$ = typeof exports != 'undefined' && exports || this;
Meteor.startup(function(){
  var PostsNeedcommentsController;
  out$.PostsNeedcommentsController = PostsNeedcommentsController = PostsListController.extend({
    view: 'needcomments'
  });
  return Router.route('/needcomments/:limit?', {
    name: 'posts_needcomments',
    controller: PostsNeedcommentsController
  });
});
viewsMenu.push({
  route: 'posts_needcomments',
  label: 'needcomments',
  description: 'Posts that need comments'
});