// Generated by LiveScript 1.3.1
Package.describe({
  summary: "Telescope Need Views View"
});
Package.on_use(function(api){
  api.use(['telescope-lib', 'telescope-base'], ['client', 'server']);
  api.add_files(['lib/needviews.js'], ['client', 'server']);
  return api.add_files(['lib/client/routes.js'], ['client']);
});