// Generated by LiveScript 1.3.1
(function(){
  Meteor.startup(function(){
    var PostsNeedViewsController;
    PostsNeedViewsController = PostsListController.extend({
      view: 'needviews'
    });
    return Router.route('/needviews/:limit?', {
      name: 'posts_needviews',
      controller: PostsNeedViewsController
    });
  });
  viewsMenu.push({
    route: 'posts_needviews',
    label: 'Need Views'
  });
}).call(this);
