// Generated by LiveScript 1.3.1
var out$ = typeof exports != 'undefined' && exports || this;
Meteor.startup(function(){
  var PostsNeedviewsController;
  out$.PostsNeedviewsController = PostsNeedviewsController = PostsListController.extend({
    view: 'needviews'
  });
  return Router.route('/needviews/:limit?', {
    name: 'posts_needviews',
    controller: PostsNeedviewsController
  });
});
viewsMenu.push({
  route: 'posts_needviews',
  label: 'needviews',
  description: 'Posts that need views'
});