// Generated by LiveScript 1.3.1
(function(){
  Package.describe({
    summary: "Telescope Need Comments View"
  });
  Package.on_use(function(api){
    api.use(['telescope-lib', 'telescope-base'], ['client', 'server']);
    api.add_files(['lib/needcomments.js'], ['client', 'server']);
    return api.add_files(['lib/client/routes.js'], ['client']);
  });
}).call(this);
