// Generated by LiveScript 1.3.1
(function(){
  viewParameters.needcomments = function(){
    return {
      options: {
        find: {
          url: {
            $exists: true
          }
        },
        sort: {
          commentCount: 1,
          viewCount: 1,
          clickCount: 1,
          postedAt: -1
        }
      }
    };
  };
}).call(this);
